language: python
group: travis_latest

git:
  depth: 25
  quiet: true

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      env: RUN_TESTS="true"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      env: RUN_TESTS="true"

before_cache:
  - rm -f /home/travis/.cache/pip/log/debug.log

cache:
  directories:
  - /home/travis/miniconda3
  - /home/travis/.cache/pip

notifications:
  email: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang
      - g++
      - gcc
      - libboost-all-dev

before_install:
  - source build_tools/travis/install.sh
#  - source activate testenv37

install: bash scripts/install_requirements.sh

before_script:
  - bash scripts/compile_engines.sh

script: bash build_tools/travis/test_script.sh
